program: train_a2c.py
method: bayes
name: Sweep_A2C
metric:
  name: mean_reward_test
  goal: maximize

parameters:
  objetivo:
    value: 0
  atraso:
    value: -1
  batch_size:
    values: [32, 64, 128, 256]
  gamma:
    min: 0.8
    max: 0.999
  learning_rate:
    min: 0.00001
    max: 0.01
  n_steps:
    values: [5, 10, 20, 50]
  gae_lambda:
    min: 0.8
    max: 1.0
  ent_coef:
    min: 0.0
    max: 0.1
  vf_coef:
    min: 0.1
    max: 1.0
  max_grad_norm:
    min: 0.5
    max: 2.0  