wandb_version: 1

batch_size:
  desc: null
  value: 128
ent_coef:
  desc: null
  value: 0.00640187240589081
gae_lambda:
  desc: null
  value: 0.9226952364371568
gamma:
  desc: null
  value: 0.8281024882955597
learning_rate:
  desc: null
  value: 0.0003894185500312607
n_epochs:
  desc: null
  value: 8
n_steps:
  desc: null
  value: 4096
target_kl:
  desc: null
  value: 0.01154855883812628
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696569247.117856
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 34
      - 37
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    session_history: code\_session_history.ipynb
