wandb_version: 1

batch_size:
  desc: null
  value: 16
ent_coef:
  desc: null
  value: 0.0016862204989332764
gae_lambda:
  desc: null
  value: 0.9989364749961802
gamma:
  desc: null
  value: 0.8645454865909222
learning_rate:
  desc: null
  value: 0.0005537730526289026
n_epochs:
  desc: null
  value: 22
n_steps:
  desc: null
  value: 3840
target_kl:
  desc: null
  value: 0.023238734085048937
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696576641.493848
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 34
      - 37
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    session_history: code\_session_history.ipynb
