wandb_version: 1

batch_size:
  desc: null
  value: 64
ent_coef:
  desc: null
  value: 0.008326888156488941
gae_lambda:
  desc: null
  value: 0.9397368197988506
gamma:
  desc: null
  value: 0.8471797768365155
learning_rate:
  desc: null
  value: 0.00031732871749220185
n_epochs:
  desc: null
  value: 28
n_steps:
  desc: null
  value: 2304
target_kl:
  desc: null
  value: 0.025634290668085313
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696568669.85073
    t:
      1:
      - 1
      - 55
      3:
      - 23
      - 34
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
