wandb_version: 1

batch_size:
  desc: null
  value: 16
ent_coef:
  desc: null
  value: 0.002434619022668416
gae_lambda:
  desc: null
  value: 0.9698217180299435
gamma:
  desc: null
  value: 0.9173765665890136
learning_rate:
  desc: null
  value: 0.0007024701613366146
n_epochs:
  desc: null
  value: 21
n_steps:
  desc: null
  value: 1024
target_kl:
  desc: null
  value: 0.02438483191976904
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696591527.686467
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 34
      - 37
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
